# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Local
spring.datasource.url=jdbc:mysql://localhost:3306/groupware?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=root

##heroku db
<<<<<<< HEAD:groupware-project/src/main/resources/application.yml
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://p8z2g20vg6mz1rp2:urdz19jcs0uh6sr4@au77784bkjx6ipju.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/o0cs86urlm8clhtn
spring.datasource.username=$groupware
spring.datasource.password=$asdf1234!
=======
#spring.datasouce.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://p8z2g20vg6mz1rp2:urdz19jcs0uh6sr4@au77784bkjx6ipju.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/o0cs86urlm8clhtn
#spring.datasource.username=$groupware
#spring.datasource.password=$asdf1234!
>>>>>>> 7c34961ec01ffdf80bfcb45ef894aa49d19c9a3b:groupware-project/src/main/resources/application.properties

# mybatis ?? ??
mybatis.mapper-locations=classpath:mapper/*.xml

#spring security ??? ?? ??
spring.security.user.name = admin
spring.security.user.password = 1234

#jpa
spring.jpa.hibernate.ddl-auto:update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
h2.console.enabled=true

#fileupload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

#session
server.servlet.session.timeout=43200
server.port=${PORT:8080}
